// <auto-generated />
using System;
using EVDMS.DataAccessLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVDMS.DataAccessLayer.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128161031_UpdateUserName")]
    partial class UpdateUserName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVDMS.Core.Model.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Config");

                    b.HasData(
                        new
                        {
                            Id = new Guid("000000c8-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Allows configuration of exterior color options.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Color",
                            VehicleId = new Guid("00000064-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Manual or automatic transmission options.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Transmission",
                            VehicleId = new Guid("00000064-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Interior material options such as leather or fabric.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Interior",
                            VehicleId = new Guid("00000064-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0004-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Selectable wheel sizes for better performance or comfort.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "WheelSize",
                            VehicleId = new Guid("00000064-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Multiple exterior paint options available.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Color",
                            VehicleId = new Guid("00000064-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0006-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Different battery capacities affecting driving range.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "BatteryPack",
                            VehicleId = new Guid("00000064-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Advanced driver assistance and autopilot features.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Autopilot",
                            VehicleId = new Guid("00000064-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0008-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Standard or premium audio system options.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "SoundSystem",
                            VehicleId = new Guid("00000064-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Selectable driving modes: Eco, Normal, Sport.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "DriveMode",
                            VehicleId = new Guid("00000064-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000a-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Standard or adaptive suspension configuration.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Suspension",
                            VehicleId = new Guid("00000064-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000b-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Flexible seating layout for passengers and cargo.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "SeatLayout",
                            VehicleId = new Guid("00000064-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000c-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Enhanced safety features and collision avoidance.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "SafetyPackage",
                            VehicleId = new Guid("00000064-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000d-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Additional towing capabilities and accessories.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "TowingPackage",
                            VehicleId = new Guid("00000064-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000e-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Panoramic glass roof or standard roof options.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "RoofType",
                            VehicleId = new Guid("00000064-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-000f-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Standard or adaptive LED lighting system.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Lighting",
                            VehicleId = new Guid("00000064-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0010-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Dual-zone or tri-zone climate control system.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "ClimateControl",
                            VehicleId = new Guid("00000064-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0011-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Gasoline or hybrid engine configurations.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "EngineType",
                            VehicleId = new Guid("00000064-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0012-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Optimized fuel consumption modes.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "FuelEfficiency",
                            VehicleId = new Guid("00000064-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0013-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Touchscreen infotainment system with navigation.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Infotainment",
                            VehicleId = new Guid("00000064-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000000c8-0014-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "Extended warranty and service plans.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Name = "Warranty",
                            VehicleId = new Guid("00000064-0005-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.Dealer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0000012c-0001-0000-0000-000000000000"),
                            Code = "DL-000",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            Email = "hungptse183180@fpt.edu.vn",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            Name = "Default Dealer"
                        },
                        new
                        {
                            Id = new Guid("0000012c-0002-0000-0000-000000000000"),
                            Code = "DL-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            Email = "hanoi.dealer@evdms.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            Name = "Hanoi Central Dealer"
                        },
                        new
                        {
                            Id = new Guid("0000012c-0003-0000-0000-000000000000"),
                            Code = "DL-002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            Email = "hcm.dealer@evdms.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            Name = "Ho Chi Minh City Dealer"
                        },
                        new
                        {
                            Id = new Guid("0000012c-0004-0000-0000-000000000000"),
                            Code = "DL-003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            Email = "danang.dealer@evdms.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            Name = "Da Nang Dealer"
                        },
                        new
                        {
                            Id = new Guid("0000012c-0005-0000-0000-000000000000"),
                            Code = "DL-004",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            Email = "cantho.dealer@evdms.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            Name = "Can Tho Dealer"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000190-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0001-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 10,
                            VehicleId = new Guid("00000064-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0001-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 8,
                            VehicleId = new Guid("00000064-0002-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0002-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 12,
                            VehicleId = new Guid("00000064-0003-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0004-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0002-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 6,
                            VehicleId = new Guid("00000064-0004-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0003-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 15,
                            VehicleId = new Guid("00000064-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0006-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0003-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 9,
                            VehicleId = new Guid("00000064-0006-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0004-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 7,
                            VehicleId = new Guid("00000064-0007-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0008-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0004-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 11,
                            VehicleId = new Guid("00000064-0008-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0005-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 5,
                            VehicleId = new Guid("00000064-0009-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000190-000a-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            DealerId = new Guid("0000012c-0005-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            Quantity = 14,
                            VehicleId = new Guid("00000064-000a-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000064-0001-0000-0000-000000000000"),
                            Description = "Staff member of a dealership.",
                            Name = "Dealer Staff"
                        },
                        new
                        {
                            Id = new Guid("00000064-0002-0000-0000-000000000000"),
                            Description = "Manager of a dealership.",
                            Name = "Dealer Manager"
                        },
                        new
                        {
                            Id = new Guid("00000064-0003-0000-0000-000000000000"),
                            Description = "Electric Vehicle Manufacturer staff.",
                            Name = "EVM Staff"
                        },
                        new
                        {
                            Id = new Guid("00000064-0004-0000-0000-000000000000"),
                            Description = "System Administrator.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000064-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "",
                            DealerId = new Guid("0000012c-0001-0000-0000-000000000000"),
                            FullName = "System Admin",
                            HashedPassword = "$2a$11$0uhjzQiyqR.PruEMpOERluaHHR2w96U8rE1ZKES9ecyACHNPnEqqm",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "",
                            RoleId = new Guid("00000064-0004-0000-0000-000000000000"),
                            UserName = "TieHung23"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedAtTick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000064-0001-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "An all-electric premium sedan produced by Tesla.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model S",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2020,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0002-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A compact electric sedan designed for mass adoption.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model 3",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2019,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0003-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A luxury electric SUV featuring falcon-wing doors.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model X",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2021,
                            VehicleType = "SUV"
                        },
                        new
                        {
                            Id = new Guid("00000064-0004-0000-0000-000000000000"),
                            Brand = "Tesla",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A versatile electric SUV designed for families.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Model Y",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2022,
                            VehicleType = "SUV"
                        },
                        new
                        {
                            Id = new Guid("00000064-0005-0000-0000-000000000000"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A reliable compact sedan with fuel-efficient performance.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Civic",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2018,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0006-0000-0000-000000000000"),
                            Brand = "Honda",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A mid-size sedan offering comfort and advanced safety.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Accord",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2019,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0007-0000-0000-000000000000"),
                            Brand = "Toyota",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A popular sedan known for durability and reliability.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Camry",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2017,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0008-0000-0000-000000000000"),
                            Brand = "Toyota",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A compact sedan with excellent fuel economy.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Corolla",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2016,
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("00000064-0009-0000-0000-000000000000"),
                            Brand = "Ford",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "An iconic sports car delivering powerful performance.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Mustang",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2021,
                            VehicleType = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("00000064-000a-0000-0000-000000000000"),
                            Brand = "Ford",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtTick = "638396640000000000",
                            CreatedBy = "System User",
                            Description = "A rugged pickup truck built for work and adventure.",
                            IsActive = true,
                            IsDeleted = false,
                            ModelName = "Ranger",
                            ModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedAtTick = "638396640000000000",
                            ModifiedBy = "System User",
                            ReleaseYear = 2022,
                            VehicleType = "Pickup"
                        });
                });

            modelBuilder.Entity("EVDMS.Core.Model.Config", b =>
                {
                    b.HasOne("EVDMS.Core.Model.Vehicle", "Vehicle")
                        .WithMany("Configs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDMS.Core.Model.Inventory", b =>
                {
                    b.HasOne("EVDMS.Core.Model.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVDMS.Core.Model.User", b =>
                {
                    b.HasOne("EVDMS.Core.Model.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVDMS.Core.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EVDMS.Core.Model.Vehicle", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
